# Если эта опция включена, то через 5 секунд после входа игрокам автоматически
# будет отправлен опрос, чтобы они отметили, откуда пришли.
# После того, как игрок ответит, опрос ему больше не будет отправляться.
# Если Вы хотите, чтобы опрос отправлялся игроку только после входа
# в аккаунт (AuthMe), то отключите эту опцию и в файле /plugins/Authme/commands.yml
# В событые onJoin запускайте команду /pts sendquestion %p от коноли.
# Это должно выглядет так:
#onLogin:
#    question:
#        command: 'pts sendquestion %p'
#        executor: 'CONSOLE'
EnableAutoQuestionSending: true

# Здесь можно указать количество выводимых игроков в одной странице
# для команды /pts list <вариант> <страница>
PlayerOnOnePage: 50

# Здесь нужно указывать варианты ответов, чтобы игроки отметили, откуда пришли.
# Изначально только 5 вариантов: monitoring, youtube, poiskovik, friends, other
# Это ключи, они будут отображаться вам при просмотре результатов.
# Игроки эти слова не будут видеть, ставьте их такими, чтобы было понятно Вам.
# Обязательно ставьте ключи в нижнем регистре! monitoring - можно, Monitoring - нельзя
# Игроки же при выборе будут видеть значения, которые вы впишете для каждого варианта.
# Просто смотрите пример ниже и всё станет понятно.
AnswerVariants:
  monitoring: ' Нашел в &lмониторинге'
  youtube: ' Нашел на &c&lYou&f&lTube'
  vk: ' Нашел во &3&l[В]контакте'
  poiskovik: ' Нашел в поисковике (&f&lGoogle&a/&f&lЯндекс &a и т. д.)'
  friends: ' Узнал от &lдрузей'
  other: ' &lДругое'